### ISSUE TITLE
Index error: string index out of range when trying to plot alignments using a reference fasta 

### ISSUE THREAD

**Issue by leticiacastillon** [StephanHolgerD/DrukBam#2]
Hi! :) Great tool to visualize specific regions of alignments! I am trying to use it together with a reference fasta, but I keep getting the following error: 

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/leti/miniconda3/envs/nanoporeProcessing/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/leti/miniconda3/envs/nanoporeProcessing/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/Users/leti/miniconda3/envs/nanoporeProcessing/lib/python3.9/site-packages/DrukBam/vcfParse.py", line 51, in PlotV
    ploter.Plot()
  File "/Users/leti/miniconda3/envs/nanoporeProcessing/lib/python3.9/site-packages/DrukBam/MapPlot.py", line 77, in Plot
    self.PlotNuc()
  File "/Users/leti/miniconda3/envs/nanoporeProcessing/lib/python3.9/site-packages/DrukBam/MapPlot.py", line 297, in PlotNuc
    self.CalcPlot.PlotNucChunk(d,self.ax,chunk[1][1],chunk[1][2],flag=self.flag)
  File "/Users/leti/miniconda3/envs/nanoporeProcessing/lib/python3.9/site-packages/DrukBam/PlotCalc.py", line 287, in PlotNucChunk
    if self.fasta != 'None' and fastaChunk[fastapos]==query_alignment_sequence[p]:
IndexError: string index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/leti/miniconda3/envs/nanoporeProcessing/bin/DrukBam", line 11, in <module>
    sys.exit(main())
  File "/Users/leti/miniconda3/envs/nanoporeProcessing/lib/python3.9/site-packages/DrukBam/__main__.py", line 101, in main
    ploter.MultiPlot()
  File "/Users/leti/miniconda3/envs/nanoporeProcessing/lib/python3.9/site-packages/DrukBam/vcfParse.py", line 59, in MultiPlot
    results = pool.starmap(self.PlotV, multi)
  File "/Users/leti/miniconda3/envs/nanoporeProcessing/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/Users/leti/miniconda3/envs/nanoporeProcessing/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
IndexError: string index out of range
/Users/leti/miniconda3/envs/nanoporeProcessing/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown  
  warnings.warn('resource_tracker: There appear to be %d '
```

This is the command I am running 
`vcf -b ../risk_alleles/sorted_reads_risk.bam -v ../VCF/testparsing.vcf --padding 100 -i test_region_1 --maxcoverage 20 --highlight --fasta ref/chr11_500k.fasta`

I do not have any issues when running it without the --fasta flag, so I am assuming there is some problem with the reference file, but I cannot figure out what it is - I made sure that all the SNPs I want to show fall within the interval of the reference genome that I dowloaded. Do you have any idea of what could be going wrong?

**Comment by StephanHolgerD** [comment]
Hello, 
I think the padding option is causing the error.
This option defines the spacing around the variant so -+100 in your case, I think at least one of your vcf entries lies somehow close to the end of the related fasta file (propably under 100nt before the end of the related sequence), so Drukbam tries to extract the needed part of the fasta and then throws the IndexError.

You could try to decrease the padding.

I will take care of this problem in the next release.

**Comment by leticiacastillon** [comment]
Unfortunately, decreasing the padding nor increasing the region selected as reference seem to help. Last I tried I used the regions of chromosome 11 from 69000000:69900000 and the following options: 

`vcf -b ../risk_alleles/sorted_reads_risk.bam -v test.vcf --padding 10 -i test_region_1 --maxcoverage 20 --highlight --fasta ref/refchr11.fasta`

and the output was the same: 

```
[('11', 69419842, 69419862), ('11', 69424963, 69424983), ('11', 69651337, 69651357)]
18it [00:00, 247.67it/s]
19it [00:00, 358.31it/s]
10it [00:00, 291.68it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/leti/miniconda3/envs/nanoporeProcessing/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/leti/miniconda3/envs/nanoporeProcessing/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/Users/leti/miniconda3/envs/nanoporeProcessing/lib/python3.9/site-packages/DrukBam/vcfParse.py", line 51, in PlotV
    ploter.Plot()
  File "/Users/leti/miniconda3/envs/nanoporeProcessing/lib/python3.9/site-packages/DrukBam/MapPlot.py", line 77, in Plot
    self.PlotNuc()
  File "/Users/leti/miniconda3/envs/nanoporeProcessing/lib/python3.9/site-packages/DrukBam/MapPlot.py", line 297, in PlotNuc
    self.CalcPlot.PlotNucChunk(d,self.ax,chunk[1][1],chunk[1][2],flag=self.flag)
  File "/Users/leti/miniconda3/envs/nanoporeProcessing/lib/python3.9/site-packages/DrukBam/PlotCalc.py", line 287, in PlotNucChunk
    if self.fasta != 'None' and fastaChunk[fastapos]==query_alignment_sequence[p]:
IndexError: string index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/leti/miniconda3/envs/nanoporeProcessing/bin/DrukBam", line 11, in <module>
    sys.exit(main())
  File "/Users/leti/miniconda3/envs/nanoporeProcessing/lib/python3.9/site-packages/DrukBam/__main__.py", line 101, in main
    ploter.MultiPlot()
  File "/Users/leti/miniconda3/envs/nanoporeProcessing/lib/python3.9/site-packages/DrukBam/vcfParse.py", line 59, in MultiPlot
    results = pool.starmap(self.PlotV, multi)
  File "/Users/leti/miniconda3/envs/nanoporeProcessing/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/Users/leti/miniconda3/envs/nanoporeProcessing/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
IndexError: string index out of range
/Users/leti/miniconda3/envs/nanoporeProcessing/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

```

**Comment by StephanHolgerD** [comment]
Are you using longread data ? I tested mainly with Illumina and some PacBio data, depending on the alignment program you used pacbio or nanopore might cause problems (probably during handeling the cigar string)
If you can share a test data set I could debug otherwise it is a little hard to find the error :)

**Comment by StephanHolgerD** [comment]
I could send you a cloud so you coukd upload dummy data set that create your error.

**Comment by leticiacastillon** [comment]
Hey, sorry for the late reply! Sure, send it and I'll try to upload a dummy
sometime this week :)

**Comment by StephanHolgerD** [comment]
https://caruscloud.uniklinikum-dresden.de/index.php/s/gRRRfbMAKkzFadY

sorry for delay, you can drop data here, link is upload only and valid for a limited time, hope the files are note super large

**Comment by StephanHolgerD** [comment]
If there are no test data I will close this issue in the next days
