### ISSUE TITLE
`ValueError: invalid literal for int() with base 10: '151=1'` in PlotCalc.py

### ISSUE THREAD

**Issue by cilliannolan** [StephanHolgerD/DrukBam#3]
Hi!

Your tool looks amazing and perfect for programmatically creating visualisations for a pipeline I am working on.
However I haven't been able to get it to run on my data, I'm getting this back, from my command:

```
DrukBam region \
    -s 1 -e 16569 -c chrM \
    -b hifi_reads.bam \
    --fasta ref.fasta \
    --outfmt png \
    -i test \
    --chunksize 16569 \
    --threads 4
```

Output:

```
9449it [01:37, 97.30it/s] 
/home/UNIXHOME/cnolan/miniconda3/envs/drukbam/lib/python3.9/site-packages/DrukBam/PlotCalc.py:149: UserWarning: FixedFormatter should only be used together with FixedLocator
  ax.set_xticklabels([str("{:,}".format(start)),str("{:,}".format(end))], rotation=40, ha='right')
Traceback (most recent call last):
  File "/home/UNIXHOME/cnolan/miniconda3/envs/drukbam/bin/DrukBam", line 11, in <module>
    sys.exit(main())
  File "/home/UNIXHOME/cnolan/miniconda3/envs/drukbam/lib/python3.9/site-packages/DrukBam/__main__.py", line 82, in main
    ploter.Plot()
  File "/home/UNIXHOME/cnolan/miniconda3/envs/drukbam/lib/python3.9/site-packages/DrukBam/MapPlot.py", line 77, in Plot
    self.PlotNuc()
  File "/home/UNIXHOME/cnolan/miniconda3/envs/drukbam/lib/python3.9/site-packages/DrukBam/MapPlot.py", line 297, in PlotNuc
    self.CalcPlot.PlotNucChunk(d,self.ax,chunk[1][1],chunk[1][2],flag=self.flag)
  File "/home/UNIXHOME/cnolan/miniconda3/envs/drukbam/lib/python3.9/site-packages/DrukBam/PlotCalc.py", line 218, in PlotNucChunk
    chunk_cigarstring=self.CigChunker(cig)
  File "/home/UNIXHOME/cnolan/miniconda3/envs/drukbam/lib/python3.9/site-packages/DrukBam/PlotCalc.py", line 180, in CigChunker
    cigL=cigL+parseCig(cig)[1]
  File "/home/UNIXHOME/cnolan/miniconda3/envs/drukbam/lib/python3.9/site-packages/DrukBam/PlotCalc.py", line 176, in parseCig
    liste=([cig[p]]*int(cig[:p]))
ValueError: invalid literal for int() with base 10: '151=1'
```

Looks like a problem with parsing a CIGAR string? Any help troubleshooting would be appreciated

**Comment by StephanHolgerD** [comment]
What program did you use to create the bam file? Seems like this is a cigarx string and not a 'classical' cigar string.

**Comment by cilliannolan** [comment]
Bam file was created using by pbAA: https://github.com/PacificBiosciences/pbAA
I'm guessing cigarx strings are not supported?

**Comment by StephanHolgerD** [comment]
Yes, unfortunately only the cigar format is supported
